# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

In [1]:
import numpy as np

In [5]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

---

In [9]:
b = np.zeros((3,3), dtype=np.int16)   
print(b)   

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [10]:
b.dtype

dtype('int16')

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

In [11]:
A = np.linspace(0,5,10,endpoint=False)
A

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

In [14]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

In [19]:
np.random.seed(10)

In [21]:
a = np.random.random((4,4))
a

array([[0.72175532, 0.29187607, 0.91777412, 0.71457578],
       [0.54254437, 0.14217005, 0.37334076, 0.67413362],
       [0.44183317, 0.43401399, 0.61776698, 0.51313824],
       [0.65039718, 0.60103895, 0.8052232 , 0.52164715]])

In [22]:
np.random.seed(0)

In [23]:
a = np.random.random((4,4))
a

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

In [26]:
a = np.arange(16)

In [29]:
a.shape

(16,)

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

In [30]:
a = np.arange(16)

In [31]:
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

In [40]:
a = np.arange(2,101,2)
a

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

In [42]:
a = np.random.randint(10,50,(6,6))
a

array([[23, 49, 31, 19, 10, 20],
       [33, 12, 44, 45, 40, 13],
       [28, 45, 30, 27, 37, 24],
       [11, 46, 20, 32, 21, 12],
       [26, 42, 10, 48, 29, 23],
       [40, 34, 12, 13, 40, 44]])

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

In [1]:
import numpy as np


array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]])

submatrix = array[1:3, 1:3]

print(submatrix)


[[ 6  7]
 [10 11]]


### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

In [45]:
c = np.arange(1,11)
print(c)
c.sum()

[ 1  2  3  4  5  6  7  8  9 10]


55

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

In [50]:
c = np.arange(1,11)
print(c)
mean = np.mean(c)
mean

[ 1  2  3  4  5  6  7  8  9 10]


5.5

In [51]:
median = np.median(c)
median

5.5

In [53]:
std = np.std(c)
std

2.8722813232690143

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

In [65]:
c = np.arange(1,11)
print(c)

[ 1  2  3  4  5  6  7  8  9 10]


In [66]:
maxi = np.max(c)
maxi

10

In [68]:
mini = np.min(c)
mini

1

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

In [71]:
B = np.random.randint(100,size=20)
B

array([34, 69, 53, 80, 62,  8, 61,  1, 81, 35, 91, 40, 36, 48, 25, 67, 35,
       30, 29, 33])

In [72]:
index_max = np.argmax(B)
index_max

10

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

In [75]:
C = np.array([1,2,3,4,5,6,7])
print(C)

[1 2 3 4 5 6 7]


In [77]:
C[::-1,]

array([7, 6, 5, 4, 3, 2, 1])

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [86]:
A = np.random.randint(10,size=(3,3))
B = np.random.randint(20,size=(3,3))
print("A=",A)
print("B=",B)

A= [[8 7 0]
 [8 6 8]
 [9 8 3]]
B= [[ 6 17  7]
 [ 2 16 18]
 [13  4  4]]


In [85]:
C = A @ B
print(C)

[[185 145 131]
 [119 123  85]
 [ 18  21  24]]


### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [7]:

A = np.array([1, 2, 3, 4])

diagonal_matrix = np.diag(A)

print(diagonal_matrix)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [6]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])

B  = np.array([[7, 8],
               [9, 10],
               [11, 12]])

C = np.dot(A, B)

print(C)


[[ 58  64]
 [139 154]]


### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [11]:
array_2D = np.array([[1, 2, 3], [2, 4, 5]])
print("Array 2D =",array_2D)
flatten_1D = array_2D.flatten()
print("After using flatten", flatten_1D)

Array 2D = [[1 2 3]
 [2 4 5]]
After using flatten [1 2 3 2 4 5]


### Exercise 21:
Stack two NumPy arrays vertically.


In [20]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])

B = np.array([[7, 8, 9], 
              [10, 11, 12]])

array_stack_ver = np.vstack((A, B))
# We can use concatenate:
array_stack_ver = np.concatenate((A, B), axis=0)

print(array_stack_ver)
print("="*13)
print(array_stack_ver)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Exercise 22:
Stack two NumPy arrays horizontally.

In [22]:
A = np.array([[1, 2, 3], 
              [4, 5, 6]])

B = np.array([[7, 8, 9], 
              [10, 11, 12]])

array_stack_hor = np.hstack((A, B))
# We can use concatenate:
array_stacked_hor = np.concatenate((A, B), axis=1)

print(array_stack_hor)
print("="*19)
print(array_stacked_hor)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


### Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [28]:
A = np.arange(12)
#split A into 3 sub-array
C = np.array_split(A,3)
print(C, "\n")
print("*"*10,"\n")
#split A into 5 sub-array
D = np.array_split(A,5)
print(D)

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])] 

********** 

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7]), array([8, 9]), array([10, 11])]


### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [5]:
A = np.random.rand(3, 3)

#Round each element to two decimal places
A_rounded = np.round(A, 2)

print("Original Random Array:")
print(A)
print("\nRounded Array:")
print(A_rounded)


Original Random Array:
[[0.07321045 0.06235432 0.31454561]
 [0.05071388 0.07372083 0.77265694]
 [0.00833021 0.33333534 0.65403461]]

Rounded Array:
[[0.07 0.06 0.31]
 [0.05 0.07 0.77]
 [0.01 0.33 0.65]]
